theme: jekyll-theme-minimal
title: Intermediate Microeconomics, 
### 2nd edition
description: The companion website to Dr. Shomu Banerjee's Intermediate Microeconomics (2021) textbook published by Routledge, UK.
show_downloads: false
